FROM mhart/alpine-node:10
RUN apk add python make gcc g++ --virtual build-dependencies
RUN npm config set unsafe-perm true && yarn config set unsafe-perm true
RUN mkdir -p /home/app/payment-rates
WORKDIR /home/app/payment-rates
COPY package*.json /home/app/payment-rates/
RUN npm i --prefer-offline
RUN npm i -g nodemon

RUN mkdir -p /home/app/payment-rates_live/
WORKDIR /home/app/payment-rates_live/

CMD ( ln -s -f /home/app/payment-rates/node_modules node_modules ) && npm run start:dev-docker
EXPOSE 3000