version: "2"
services:
  app:
    container_name: payment-rates
    build: .
    restart: always
    build: .
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo-payments-rates
    image: mvertes/alpine-mongo:4.0.3-0
    volumes:
      - ./data:/data/db
    ports:
      - "27017:27017"